/**
 * PX4 event metadata: bundled definitions plus the lookup the MAVLink handler
 * calls when an EVENT (410) arrives.
 *
 * The bundled JSON is generated by scripts/generate-px4-event-metadata.mjs from
 * PX4's own all_events.json.xz, so it matches stock PX4 for the release the
 * SITL bundles are built from. A vehicle running a custom build can serve its
 * own copy over MAVLink FTP; setPx4EventMetadata() exists so that fetched copy
 * can replace the bundled one at runtime without touching the call sites.
 */

import {
  buildPx4EventIndex,
  formatPx4EventMessage,
  px4EventSeverity,
  type Px4EventIndex,
  type Px4EventMetadata,
} from './px4-event-format.js';
// resolveJsonModule is enabled; rollup inlines this into the main bundle, so it
// works in dev and inside the packaged asar with no path resolution.
import bundledMetadata from './px4-event-metadata.json' assert { type: 'json' };

let index: Px4EventIndex | null = null;
let usingBundled = true;

function getIndex(): Px4EventIndex {
  if (!index) index = buildPx4EventIndex(bundledMetadata as Px4EventMetadata);
  return index;
}

/**
 * Replace the bundled definitions with a copy fetched from the vehicle. Pass
 * null to fall back to the bundled set (e.g. on disconnect).
 */
export function setPx4EventMetadata(metadata: Px4EventMetadata | null): void {
  index = metadata ? buildPx4EventIndex(metadata) : null;
  usingBundled = metadata === null;
}

export function isUsingBundledPx4EventMetadata(): boolean {
  return usingBundled;
}

export interface FormattedPx4Event {
  /** Rendered sentence, e.g. "No valid global position estimate". */
  text: string;
  /** MAV_SEVERITY-compatible level, or null when the event is not user-facing. */
  severity: number | null;
  /** PX4's internal event name, useful for logs and for matching in tests. */
  name?: string;
  /** 'default' | 'arming_check' | 'health' | 'calibration' */
  group: string;
}

/**
 * Resolve an EVENT to displayable text. Returns null for an unknown id (a
 * custom build, or metadata older than the firmware) so the caller can decide
 * whether to show a placeholder.
 */
export function formatPx4Event(id: number, args: Uint8Array, logLevels: number): FormattedPx4Event | null {
  const entry = getIndex().get(id);
  if (!entry) return null;

  const text = formatPx4EventMessage(entry, args);
  if (!text) return null;

  return {
    text,
    severity: px4EventSeverity(logLevels),
    name: entry.def.name,
    group: entry.group,
  };
}

export { px4EventSeverity };
